# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'concrete-swift' do

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.0.0-beta.3'
pod 'SDWebImage'

end

target 'concrete-swiftTests' do

end

target 'concrete-swiftUITests' do

end

