# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'concrete-swift' do

pod 'Alamofire'
pod 'SDWebImage'
pod 'Genome'

end

target 'concrete-swiftTests' do

end

target 'concrete-swiftUITests' do

end

